USE car_wash;

CREATE TABLE IF NOT EXISTS `SW_APPLICATION` (
  `SW_APP_APPLICATIONID` varchar(64) NOT NULL,
  `SW_APP_KEY` varchar(255) NOT NULL DEFAULT '',
  `SW_APP_TYPE` int NOT NULL DEFAULT '0',
  `SW_APP_AVATAR` varchar(500) DEFAULT NULL,
  `SW_APP_COMPANY` varchar(255) DEFAULT NULL,
  `SW_APP_CREATEIME` datetime DEFAULT NULL,
  `SW_APP_CREATOR` varchar(64) DEFAULT NULL,
  `SW_APP_INITPIC` varchar(500) DEFAULT NULL,
  `SW_APP_NAME` varchar(255) DEFAULT NULL,
  `SW_APP_NOTE` text,
  `SW_APP_OWNER` varchar(64) DEFAULT NULL,
  `SW_APP_RELEASETIME` datetime DEFAULT NULL,
  `SW_APP_UPDATETIME` datetime DEFAULT NULL,
  `SW_APP_URL` varchar(500) DEFAULT NULL,
  `SW_APP_VERSION` varchar(100) DEFAULT NULL,
  `SW_APP_CON` text,
  `SW_APP_VIEW` bigint DEFAULT NULL,
  PRIMARY KEY (`SW_APP_APPLICATIONID`)
);

CREATE TABLE IF NOT EXISTS `SW_STOREDB` (
  `SW_STORE_STOREID` varchar(64) NOT NULL,
  `SW_STORE_NAME` varchar(255) DEFAULT NULL,
  `SW_STORE_CON` text,
  `SW_STORE_Note` text,
  PRIMARY KEY (`SW_STORE_STOREID`)
);

CREATE TABLE IF NOT EXISTS `SW_APPLICATION_SW_STOREDB` (
  `SW_APPLICATION_ID` varchar(64) NOT NULL,
  `SW_STOREDB_ID` varchar(64) NOT NULL,
  PRIMARY KEY (`SW_APPLICATION_ID`, `SW_STOREDB_ID`),
  KEY `ix_application_storedb` (`SW_STOREDB_ID`)
);
