USE car_wash;

CREATE TABLE IF NOT EXISTS `SW_APPLICATION` (
  `SW_APP_APPLICATIONID` varchar(64) NOT NULL,
  `SW_APP_KEY` varchar(255) NOT NULL DEFAULT '',
  `SW_APP_TYPE` int NOT NULL DEFAULT '0',
  `SW_APP_AVATAR` varchar(500) DEFAULT NULL,
  `SW_APP_COMPANY` varchar(255) DEFAULT NULL,
  `SW_APP_CREATEIME` datetime DEFAULT NULL,
  `SW_APP_CREATOR` varchar(64) DEFAULT NULL,
  `SW_APP_INITPIC` varchar(500) DEFAULT NULL,
  `SW_APP_NAME` varchar(255) DEFAULT NULL,
  `SW_APP_NOTE` text,
  `SW_APP_OWNER` varchar(64) DEFAULT NULL,
  `SW_APP_RELEASETIME` datetime DEFAULT NULL,
  `SW_APP_UPDATETIME` datetime DEFAULT NULL,
  `SW_APP_URL` varchar(500) DEFAULT NULL,
  `SW_APP_VERSION` varchar(100) DEFAULT NULL,
  `SW_APP_CON` text,
  `SW_APP_VIEW` bigint DEFAULT NULL,
  PRIMARY KEY (`SW_APP_APPLICATIONID`)
);

CREATE TABLE IF NOT EXISTS `SW_STOREDB` (
  `SW_STORE_STOREID` varchar(64) NOT NULL,
  `SW_STORE_NAME` varchar(255) DEFAULT NULL,
  `SW_STORE_CON` text,
  `SW_STORE_Note` text,
  PRIMARY KEY (`SW_STORE_STOREID`)
);

CREATE TABLE IF NOT EXISTS `SW_APPLICATION_SW_STOREDB` (
  `SW_APPLICATION_ID` varchar(64) NOT NULL,
  `SW_STOREDB_ID` varchar(64) NOT NULL,
  PRIMARY KEY (`SW_APPLICATION_ID`, `SW_STOREDB_ID`),
  KEY `ix_application_storedb` (`SW_STOREDB_ID`)
);

INSERT INTO `SW_STOREDB` (`SW_STORE_STOREID`, `SW_STORE_NAME`, `SW_STORE_CON`, `SW_STORE_Note`)
VALUES ('car_wash', 'car_wash', 'Url=jdbc:mysql://mysql:3306/car_wash?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true;User ID=root;Password=Pa88word', 'Docker MySQL smoke database')
ON DUPLICATE KEY UPDATE
  `SW_STORE_NAME` = VALUES(`SW_STORE_NAME`),
  `SW_STORE_CON` = VALUES(`SW_STORE_CON`),
  `SW_STORE_Note` = VALUES(`SW_STORE_Note`);

INSERT INTO `SW_APPLICATION` (
  `SW_APP_APPLICATIONID`, `SW_APP_KEY`, `SW_APP_TYPE`, `SW_APP_AVATAR`,
  `SW_APP_COMPANY`, `SW_APP_CREATEIME`, `SW_APP_CREATOR`, `SW_APP_INITPIC`,
  `SW_APP_NAME`, `SW_APP_NOTE`, `SW_APP_OWNER`, `SW_APP_RELEASETIME`,
  `SW_APP_UPDATETIME`, `SW_APP_URL`, `SW_APP_VERSION`, `SW_APP_CON`, `SW_APP_VIEW`
)
VALUES (
  'fool-service', 'fool-service', 0, NULL, NULL, NOW(), 'admin', NULL,
  'Fool Service', 'Docker smoke application', 'admin', NULL, NOW(), NULL,
  '1.0.0', 'Url=jdbc:mysql://mysql:3306/car_wash?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true;User ID=root;Password=Pa88word', 100
)
ON DUPLICATE KEY UPDATE
  `SW_APP_KEY` = VALUES(`SW_APP_KEY`),
  `SW_APP_TYPE` = VALUES(`SW_APP_TYPE`),
  `SW_APP_CREATOR` = VALUES(`SW_APP_CREATOR`),
  `SW_APP_NAME` = VALUES(`SW_APP_NAME`),
  `SW_APP_NOTE` = VALUES(`SW_APP_NOTE`),
  `SW_APP_OWNER` = VALUES(`SW_APP_OWNER`),
  `SW_APP_UPDATETIME` = VALUES(`SW_APP_UPDATETIME`),
  `SW_APP_VERSION` = VALUES(`SW_APP_VERSION`),
  `SW_APP_CON` = VALUES(`SW_APP_CON`),
  `SW_APP_VIEW` = VALUES(`SW_APP_VIEW`);

INSERT IGNORE INTO `SW_APPLICATION_SW_STOREDB` (`SW_APPLICATION_ID`, `SW_STOREDB_ID`)
VALUES ('fool-service', 'car_wash');
