USE car_wash;

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_COMPANY` (
  `APP_COR_ID` bigint NOT NULL AUTO_INCREMENT,
  `APP_COR_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`APP_COR_ID`)
);

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_DEPARTMENT` (
  `APP_DEP_ID` bigint NOT NULL AUTO_INCREMENT,
  `APP_DEP_NAME` varchar(255) DEFAULT NULL,
  `APP_DEP_DEFAULTVIEW` bigint DEFAULT NULL,
  `SW_APP_AUTH_COMPANY_DepsAPP_COR_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`APP_DEP_ID`),
  KEY `ix_auth_department_company` (`SW_APP_AUTH_COMPANY_DepsAPP_COR_ID`)
);

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_DEPARTMENT_SubDepartments` (
  `SW_APP_AUTH_DEPARTMENT_SubDepartmentsAPP_DEP_ID` bigint NOT NULL,
  `SW_APP_AUTH_DEPARTMENT_SUBDEPARTMENTS_ITEM` bigint NOT NULL,
  PRIMARY KEY (`SW_APP_AUTH_DEPARTMENT_SubDepartmentsAPP_DEP_ID`, `SW_APP_AUTH_DEPARTMENT_SUBDEPARTMENTS_ITEM`),
  KEY `ix_auth_department_sub_item` (`SW_APP_AUTH_DEPARTMENT_SUBDEPARTMENTS_ITEM`)
);

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_USER` (
  `APP_AUTH_ID` bigint NOT NULL AUTO_INCREMENT,
  `APP_AUTH_USERID` varchar(64) DEFAULT NULL,
  `APP_AUTH_USERLOGINNAME` varchar(255) DEFAULT NULL,
  `APP_AUTH_DEP` bigint DEFAULT NULL,
  PRIMARY KEY (`APP_AUTH_ID`),
  KEY `ix_app_auth_userid` (`APP_AUTH_USERID`),
  KEY `ix_app_auth_dep` (`APP_AUTH_DEP`)
);

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_USER_SW_EVT_DEF` (
  `SW_APP_AUTH_USER_ID` bigint NOT NULL,
  `SW_EVT_DEF_ID` varchar(36) NOT NULL,
  PRIMARY KEY (`SW_APP_AUTH_USER_ID`, `SW_EVT_DEF_ID`),
  KEY `ix_evt_def_notify_user` (`SW_EVT_DEF_ID`)
);

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_MENU` (
  `AUTH_MENU_ID` bigint NOT NULL AUTO_INCREMENT,
  `AUTH_MENU_TEXT` varchar(255) DEFAULT NULL,
  `AUTH_MENU_SHORTCUTKEY` varchar(255) DEFAULT NULL,
  `AUTH_MENU_IMAGE` varchar(500) DEFAULT NULL,
  `AUTH_MENU_VISIABLE` tinyint(1) NOT NULL DEFAULT '0',
  `AUTH_MENU_ENABLE` tinyint(1) NOT NULL DEFAULT '0',
  `AUTH_MENU_VIEWID` bigint NOT NULL DEFAULT '0',
  `AUTH_MENU_TEMPLATEFILE` varchar(500) DEFAULT NULL,
  `AUTH_MENU_INDEX` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`AUTH_MENU_ID`)
);

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_MENU_SubItems` (
  `SW_APP_AUTH_MENU_SubItemsAUTH_MENU_ID` bigint NOT NULL,
  `SW_APP_AUTH_MENU_SUBITEMS_ITEM` bigint NOT NULL,
  PRIMARY KEY (`SW_APP_AUTH_MENU_SubItemsAUTH_MENU_ID`, `SW_APP_AUTH_MENU_SUBITEMS_ITEM`),
  KEY `ix_auth_menu_sub_item` (`SW_APP_AUTH_MENU_SUBITEMS_ITEM`)
);

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_ROLE` (
  `AUTH_ROLE_ID` bigint NOT NULL AUTO_INCREMENT,
  `AUTH_ROLE_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`AUTH_ROLE_ID`)
);

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_MENU_SW_APP_AUTH_ROLE` (
  `SW_APP_AUTH_MENU_ID` bigint NOT NULL,
  `SW_APP_AUTH_ROLE_ID` bigint NOT NULL,
  PRIMARY KEY (`SW_APP_AUTH_MENU_ID`, `SW_APP_AUTH_ROLE_ID`),
  KEY `ix_role_menu_role` (`SW_APP_AUTH_ROLE_ID`)
);

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_ROLE_SW_EVT_DEF` (
  `SW_APP_AUTH_ROLE_ID` bigint NOT NULL,
  `SW_EVT_DEF_ID` varchar(36) NOT NULL,
  PRIMARY KEY (`SW_APP_AUTH_ROLE_ID`, `SW_EVT_DEF_ID`),
  KEY `ix_evt_def_notify_role` (`SW_EVT_DEF_ID`)
);

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_ROLE_SW_APP_AUTH_USER` (
  `SW_APP_AUTH_ROLE_ID` bigint NOT NULL,
  `SW_APP_AUTH_USER_ID` bigint NOT NULL,
  PRIMARY KEY (`SW_APP_AUTH_ROLE_ID`, `SW_APP_AUTH_USER_ID`),
  KEY `ix_role_auth_user` (`SW_APP_AUTH_USER_ID`)
);

CREATE TABLE IF NOT EXISTS `SW_SYS_MODULE` (
  `MODULE_NAME` varchar(255) NOT NULL,
  `MODULE_REMARK` varchar(500) DEFAULT NULL,
  `MODULE_ASSEMBLY` varchar(255) DEFAULT NULL,
  `MODULE_FILENAME` varchar(500) DEFAULT NULL,
  `MODULE_VERSION` varchar(64) DEFAULT NULL,
  `MODULE_GENERATIONCODE` tinyint(1) NOT NULL DEFAULT '1',
  `MODULE_CON` text,
  PRIMARY KEY (`MODULE_NAME`)
);

CREATE TABLE IF NOT EXISTS `SW_SYS_VIEW` (
  `VIEW_ID` bigint NOT NULL AUTO_INCREMENT,
  `VIEW_NAME` varchar(255) DEFAULT NULL,
  `VIEW_CONTYPE` int NOT NULL DEFAULT '2',
  PRIMARY KEY (`VIEW_ID`),
  KEY `ix_sw_sys_view_name` (`VIEW_NAME`)
);

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_DEPARTMENT_SW_EVT_DEF` (
  `SW_APP_AUTH_DEPARTMENT_ID` bigint NOT NULL,
  `SW_EVT_DEF_ID` varchar(36) NOT NULL,
  PRIMARY KEY (`SW_APP_AUTH_DEPARTMENT_ID`, `SW_EVT_DEF_ID`),
  KEY `ix_evt_def_notify_department` (`SW_EVT_DEF_ID`)
);

CREATE TABLE IF NOT EXISTS `SW_APP_AUTH_COMPANY_SW_EVT_DEF` (
  `SW_APP_AUTH_COMPANY_ID` bigint NOT NULL,
  `SW_EVT_DEF_ID` varchar(36) NOT NULL,
  PRIMARY KEY (`SW_APP_AUTH_COMPANY_ID`, `SW_EVT_DEF_ID`),
  KEY `ix_evt_def_notify_company` (`SW_EVT_DEF_ID`)
);

CREATE TABLE IF NOT EXISTS `SW_EVT_DEF` (
  `EVTDEF_ID` varchar(36) NOT NULL,
  `EVTDEF_FILTER` text,
  `EVTDEF_VIEW` varchar(64) DEFAULT NULL,
  `EVTDEF_OPERATION` varchar(64) DEFAULT NULL,
  `EVTDEF_MSGFMT` text,
  `EVTDEF_TIMEOUTSECS` int DEFAULT NULL,
  `EVTDEF_MODEL` varchar(64) DEFAULT NULL,
  `EVTDEF_MODELREF` int DEFAULT NULL,
  `EVTDEF_STATE` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`EVTDEF_ID`)
);

CREATE TABLE IF NOT EXISTS `SW_EVT_EVENT` (
  `EVT_ID` varchar(36) NOT NULL,
  `EVT_CREATETIME` datetime DEFAULT NULL,
  `EVT_MSG` text,
  `EVT_DEALMSG` text,
  `EVT_DEALTIME` datetime DEFAULT NULL,
  `EVT_DEALUSER` varchar(64) DEFAULT NULL,
  `EVT_VIEW` varchar(64) DEFAULT NULL,
  `EVT_DEF` varchar(255) DEFAULT NULL,
  `EVT_Defination` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`EVT_ID`),
  KEY `ix_evt_definition_object` (`EVT_Defination`, `EVT_DEF`)
);

CREATE TABLE IF NOT EXISTS `SW_SYS_MSG` (
  `MSG_ID` varchar(36) NOT NULL,
  `MSG_EVT` varchar(36) DEFAULT NULL,
  `MSG_VIEW` varchar(64) DEFAULT NULL,
  `MSG_OBJ` varchar(255) DEFAULT NULL,
  `MSG_MSG` text,
  `MSG_CREATETIME` datetime DEFAULT NULL,
  `MSG_READTIME` datetime DEFAULT NULL,
  `MSG_PUSHTIME` datetime DEFAULT NULL,
  `MSG_ENDLINETIME` datetime DEFAULT NULL,
  `MSG_STATE` int NOT NULL DEFAULT '0',
  `MSG_READOPERATION` varchar(64) DEFAULT NULL,
  `MSG_USERID` varchar(64) DEFAULT NULL,
  `MSG_MSGTYPE` int DEFAULT NULL,
  PRIMARY KEY (`MSG_ID`),
  KEY `ix_msg_evt` (`MSG_EVT`),
  KEY `ix_msg_user_state` (`MSG_USERID`, `MSG_STATE`)
);
