USE car_wash;

CREATE TABLE IF NOT EXISTS `SW_AUTH_USER` (
  `USER_UID` bigint NOT NULL AUTO_INCREMENT,
  `USER_UUID` varchar(36) DEFAULT NULL,
  `USER_LOGINNAME` varchar(255) DEFAULT NULL,
  `USER_PHONE` varchar(64) DEFAULT NULL,
  `USER_MAIL` varchar(255) DEFAULT NULL,
  `USER_FIRSTNAME` varchar(255) DEFAULT NULL,
  `USER_LASTNAME` varchar(255) DEFAULT NULL,
  `USER_SHOWNAME` varchar(255) DEFAULT NULL,
  `USER_TITLE` varchar(255) DEFAULT NULL,
  `USER_AVTAR` varchar(500) DEFAULT NULL,
  `USER_PWD` varchar(255) DEFAULT NULL,
  `USER_REGTIME` datetime DEFAULT NULL,
  `USER_LASTLOGINTIME` datetime DEFAULT NULL,
  `USER_LASTMODIFYTIME` datetime DEFAULT NULL,
  `USER_SEX` int DEFAULT NULL,
  `USER_DEFAULTVIEW` bigint DEFAULT NULL,
  PRIMARY KEY (`USER_UID`),
  UNIQUE KEY `uk_sw_auth_user_uuid` (`USER_UUID`),
  UNIQUE KEY `uk_sw_auth_user_loginname` (`USER_LOGINNAME`),
  UNIQUE KEY `uk_sw_auth_user_phone` (`USER_PHONE`),
  UNIQUE KEY `uk_sw_auth_user_mail` (`USER_MAIL`)
);

CREATE TABLE IF NOT EXISTS `auth_user` (
  `id` varchar(64) NOT NULL,
  `mobile` varchar(64) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `last_login` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `auth_role` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `auth_item` (
  `id` varchar(64) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `auth_type` int NOT NULL DEFAULT '0',
  `auth_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `auth_user_role` (
  `user_id` varchar(64) NOT NULL,
  `role_id` bigint NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  KEY `ix_auth_user_role_role` (`role_id`)
);

CREATE TABLE IF NOT EXISTS `auth_role_auth` (
  `role_id` bigint NOT NULL,
  `auth_id` varchar(64) NOT NULL,
  PRIMARY KEY (`role_id`, `auth_id`),
  KEY `ix_auth_role_auth_auth` (`auth_id`)
);

INSERT INTO `auth_user` (`id`, `mobile`, `name`, `password`)
VALUES ('admin', '', 'Admin', LOWER(MD5(CONCAT('admin', 'admin'))))
ON DUPLICATE KEY UPDATE
  `mobile` = VALUES(`mobile`),
  `name` = VALUES(`name`),
  `password` = VALUES(`password`);

INSERT INTO `auth_role` (`id`, `name`)
VALUES (1, 'Admin')
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`);

INSERT INTO `auth_item` (`id`, `name`, `auth_type`, `auth_name`)
VALUES
  ('01', 'Views', 2, NULL),
  ('0101', 'OrderList', 1, 'OrderList')
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `auth_type` = VALUES(`auth_type`),
  `auth_name` = VALUES(`auth_name`);

INSERT IGNORE INTO `auth_user_role` (`user_id`, `role_id`)
VALUES ('admin', 1);

INSERT IGNORE INTO `auth_role_auth` (`role_id`, `auth_id`)
VALUES
  (1, '01'),
  (1, '0101');

INSERT INTO `SW_AUTH_USER` (
  `USER_UID`, `USER_UUID`, `USER_LOGINNAME`, `USER_PHONE`, `USER_MAIL`,
  `USER_FIRSTNAME`, `USER_LASTNAME`, `USER_SHOWNAME`, `USER_TITLE`,
  `USER_AVTAR`, `USER_PWD`, `USER_REGTIME`, `USER_LASTLOGINTIME`,
  `USER_LASTMODIFYTIME`, `USER_SEX`, `USER_DEFAULTVIEW`
)
VALUES (1, 'admin', 'admin', '', '', 'Admin', '', 'Admin', NULL, NULL, '19a2854144b63a8f7617a6f22519b12', NOW(), NULL, NOW(), NULL, 100)
ON DUPLICATE KEY UPDATE
  `USER_LOGINNAME` = VALUES(`USER_LOGINNAME`),
  `USER_SHOWNAME` = VALUES(`USER_SHOWNAME`),
  `USER_PWD` = VALUES(`USER_PWD`),
  `USER_DEFAULTVIEW` = VALUES(`USER_DEFAULTVIEW`);

INSERT INTO `SW_APP_AUTH_USER` (`APP_AUTH_ID`, `APP_AUTH_USERID`, `APP_AUTH_USERLOGINNAME`, `APP_AUTH_DEP`)
VALUES (1, 'admin', 'admin', NULL)
ON DUPLICATE KEY UPDATE
  `APP_AUTH_USERID` = VALUES(`APP_AUTH_USERID`),
  `APP_AUTH_USERLOGINNAME` = VALUES(`APP_AUTH_USERLOGINNAME`),
  `APP_AUTH_DEP` = VALUES(`APP_AUTH_DEP`);

INSERT INTO `SW_APP_AUTH_ROLE` (`AUTH_ROLE_ID`, `AUTH_ROLE_NAME`)
VALUES (1, 'Admin')
ON DUPLICATE KEY UPDATE
  `AUTH_ROLE_NAME` = VALUES(`AUTH_ROLE_NAME`);

INSERT INTO `SW_APP_AUTH_MENU` (
  `AUTH_MENU_ID`, `AUTH_MENU_TEXT`, `AUTH_MENU_SHORTCUTKEY`, `AUTH_MENU_IMAGE`,
  `AUTH_MENU_VISIABLE`, `AUTH_MENU_ENABLE`, `AUTH_MENU_VIEWID`,
  `AUTH_MENU_TEMPLATEFILE`, `AUTH_MENU_INDEX`
)
VALUES
  (1, 'Views', NULL, NULL, 1, 1, 0, NULL, 1),
  (2, 'OrderList', NULL, NULL, 1, 1, 100, NULL, 1)
ON DUPLICATE KEY UPDATE
  `AUTH_MENU_TEXT` = VALUES(`AUTH_MENU_TEXT`),
  `AUTH_MENU_SHORTCUTKEY` = VALUES(`AUTH_MENU_SHORTCUTKEY`),
  `AUTH_MENU_IMAGE` = VALUES(`AUTH_MENU_IMAGE`),
  `AUTH_MENU_VISIABLE` = VALUES(`AUTH_MENU_VISIABLE`),
  `AUTH_MENU_ENABLE` = VALUES(`AUTH_MENU_ENABLE`),
  `AUTH_MENU_VIEWID` = VALUES(`AUTH_MENU_VIEWID`),
  `AUTH_MENU_TEMPLATEFILE` = VALUES(`AUTH_MENU_TEMPLATEFILE`),
  `AUTH_MENU_INDEX` = VALUES(`AUTH_MENU_INDEX`);

INSERT IGNORE INTO `SW_APP_AUTH_MENU_SubItems` (`SW_APP_AUTH_MENU_SubItemsAUTH_MENU_ID`, `SW_APP_AUTH_MENU_SUBITEMS_ITEM`)
VALUES (1, 2);

INSERT IGNORE INTO `SW_APP_AUTH_ROLE_SW_APP_AUTH_USER` (`SW_APP_AUTH_ROLE_ID`, `SW_APP_AUTH_USER_ID`)
VALUES (1, 1);

INSERT IGNORE INTO `SW_APP_AUTH_MENU_SW_APP_AUTH_ROLE` (`SW_APP_AUTH_MENU_ID`, `SW_APP_AUTH_ROLE_ID`)
VALUES
  (1, 1),
  (2, 1);
